### ISSUE TITLE
Warcraft: Create Project （Chinese：创建项目失败）

### ISSUE THREAD

**Issue by a67793581** [warcraft-iii/warcraft-vscode#15]
user.settings.json
`
{
    //-------- HTTP configuration --------
    // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
    // "http.proxy": "http://127.0.0.1:8080", //your corporate proxy
    // Whether the proxy server certificate should be verified against the list of supplied CAs.
    // "http.proxyStrictSSL": false,
    "vetur.format.defaultFormatter.html": "js-beautify-html",
    "vetur.format.defaultFormatterOptions": {
        "js-beautify-html": {
            "wrap_attributes": "force-aligned" //属性强制折行对齐
        }
    },
    //验证文件类型
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "vue",
        "html",
        "jsx",
    ],
    "prettier.singleQuote": true, //使用单引号而不是双引号
    "prettier.jsxBracketSameLine": true, //将>多行JSX元素放在最后一行的末尾，而不是单独放在下一行
    "editor.formatOnSave": true,
    "explorer.confirmDelete": false,
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "warcraft.autoCloseClient": true,
    "warcraft.gamePath": "D:\\Program Files (x86)\\dzclient\\Game\\Warcraft_1.32.8\\_retail_\\x86_64\\Warcraft III Backup.exe",
    "warcraft.wePath": "D:\\Program Files (x86)\\dzclient\\Game\\Warcraft_1.32.8\\_retail_\\x86_64\\Warcraft III.exe",
    "warcraft.gameArgs": [
        "-launch"
    ],
    "warcraft.libraryOrganizations": [], //保存时自动格式化
}
`
![企业微信截图_16028595677760](https://user-images.githubusercontent.com/18513362/96273542-0a141780-1002-11eb-923e-a61e52eb6abb.png)
![企业微信截图_16028596445094](https://user-images.githubusercontent.com/18513362/96273565-10a28f00-1002-11eb-92c5-1d0a6addd302.png)
![企业微信截图_16028594557616](https://user-images.githubusercontent.com/18513362/96273672-3039b780-1002-11eb-98c8-bba7d361ebbc.png)

**Comment by dulingzhi** [comment]
是从github下载模板，请确保可以访问
